=== wiltonlazary/vespa/vespalib/src/vespa/fastlib/text/alphasort/AlphaSort1_0.dtd
<!--  (c) 2002 Fast Search & Transfer. All rights reserved.  -->
<!-- Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root. -->
<!--  Version 1.0 -->

<!ELEMENT sortOrder (sortValue*)>
<!ELEMENT sortValue (unicode*)>
<!ELEMENT unicode (hex|decimal|utf8)>
<!ELEMENT hex (#PCDATA)>
<!ELEMENT decimal (#PCDATA)>
<!ELEMENT utf8 (#PCDATA)>

=== wiltonlazary/vespa/vespalib/src/vespa/fastlib/text/alphasort/Greek.xml
<?xml version="1.0"?>
<!-- Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root. -->
<!DOCTYPE sortOrder SYSTEM "AlphaSort1_0.dtd">
<sortOrder>  
   <sortValue>
      <unicode>
         <hex> 0391 </hex>
      </unicode>
      <unicode>
         <hex> 03B1 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0392 </hex>
      </unicode>
      <unicode>
         <hex> 03B2 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0393 </hex>
      </unicode>
      <unicode>
         <hex> 03B3 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0394 </hex>
      </unicode>
      <unicode>
         <hex> 03B4 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0395 </hex>
      </unicode>
      <unicode>
         <hex> 03B5 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0396 </hex>
      </unicode>
      <unicode>
         <hex> 03B6 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0397 </hex>
      </unicode>
      <unicode>
         <hex> 03B7 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0398 </hex>
      </unicode>
      <unicode>
         <hex> 03B8 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0399 </hex>
      </unicode>
      <unicode>
         <hex> 03B9 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 039A </hex>
      </unicode>
      <unicode>
         <hex> 03BA </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 039B </hex>
      </unicode>
      <unicode>
         <hex> 03BB </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 039C </hex>
      </unicode>
      <unicode>
         <hex> 03BC </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 039D </hex>
      </unicode>
      <unicode>
         <hex> 03BD </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 039E </hex>
      </unicode>
      <unicode>
         <hex> 03BE </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 039F </hex>
      </unicode>
      <unicode>
         <hex> 03BF </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 03A0 </hex>
      </unicode>
      <unicode>
         <hex> 03C0 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 03A1 </hex>
      </unicode>
      <unicode>
         <hex> 03C1 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 03A2 </hex>
      </unicode>
      <unicode>
         <hex> 03C2 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 03A3 </hex>
      </unicode>
      <unicode>
         <hex> 03C3 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 03A4 </hex>
      </unicode>
      <unicode>
         <hex> 03C4 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 03A5 </hex>
      </unicode>
      <unicode>
         <hex> 03C5 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 03A6 </hex>
      </unicode>
      <unicode>
         <hex> 03C6 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 03A7 </hex>
      </unicode>
      <unicode>
         <hex> 03C7 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 03A8 </hex>
      </unicode>
      <unicode>
         <hex> 03C8 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 03A9 </hex>
      </unicode>
      <unicode>
         <hex> 03C9 </hex>
      </unicode>
   </sortValue>
</sortOrder>

=== wiltonlazary/vespa/vespalib/src/vespa/fastlib/text/alphasort/Numbers.xml
<?xml version="1.0"?>
<!-- Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root. -->
<!DOCTYPE sortOrder SYSTEM "AlphaSort1_0.dtd">
<sortOrder>  
   <sortValue>
      <unicode>
         <hex> 30 </hex>
      </unicode>
      <unicode>
         <hex> 660 </hex>
      </unicode>
      <unicode>
         <hex> 6F0 </hex>
      </unicode>
      <unicode>
         <hex> FF10 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 31 </hex>
      </unicode>
      <unicode>
         <hex> 661 </hex>
      </unicode>
      <unicode>
         <hex> 6F1 </hex>
      </unicode>
      <unicode>
         <hex> FF11 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 32 </hex>
      </unicode>
      <unicode>
         <hex> 662 </hex>
      </unicode>
      <unicode>
         <hex> 6F2 </hex>
      </unicode>
      <unicode>
         <hex> FF12 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 33 </hex>
      </unicode>
      <unicode>
         <hex> 663 </hex>
      </unicode>
      <unicode>
         <hex> 6F3 </hex>
      </unicode>
      <unicode>
         <hex> FF13 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 34 </hex>
      </unicode>
      <unicode>
         <hex> 664 </hex>
      </unicode>
      <unicode>
         <hex> 6F4 </hex>
      </unicode>
      <unicode>
         <hex> FF14 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 35 </hex>
      </unicode>
      <unicode>
         <hex> 665 </hex>
      </unicode>
      <unicode>
         <hex> 6F5 </hex>
      </unicode>
      <unicode>
         <hex> FF15 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 36 </hex>
      </unicode>
      <unicode>
         <hex> 666 </hex>
      </unicode>
      <unicode>
         <hex> 6F6 </hex>
      </unicode>
      <unicode>
         <hex> FF16 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 37 </hex>
      </unicode>
      <unicode>
         <hex> 667 </hex>
      </unicode>
      <unicode>
         <hex> 6F7 </hex>
      </unicode>
      <unicode>
         <hex> FF17 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 38 </hex>
      </unicode>
      <unicode>
         <hex> 668 </hex>
      </unicode>
      <unicode>
         <hex> 6F8 </hex>
      </unicode>
      <unicode>
         <hex> FF18 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 39 </hex>
      </unicode>
      <unicode>
         <hex> 669 </hex>
      </unicode>
      <unicode>
         <hex> 6F9 </hex>
      </unicode>
      <unicode>
         <hex> FF19 </hex>
      </unicode>
   </sortValue>
</sortOrder>

=== wiltonlazary/vespa/vespalib/src/vespa/fastlib/text/alphasort/Hebrew.xml
<?xml version="1.0"?>
<!-- Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root. -->
<!DOCTYPE sortOrder SYSTEM "AlphaSort1_0.dtd">
<sortOrder>  
   <sortValue>
      <unicode>
         <hex> 05D0 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05D1 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05D2 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05D3 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05D4 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05D5 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05D6 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05D7 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05D8 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05D9 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05DA </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05DB </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05DC </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05DD </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05DE </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05DF </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05E0 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05E1 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05E2 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05E3 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05E4 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05E5 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05E6 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05E7 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05E8 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05E9 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 05EA </hex>
      </unicode>
   </sortValue>
</sortOrder>

=== wiltonlazary/vespa/vespalib/src/vespa/fastlib/text/alphasort/Cyrillic.xml
<?xml version="1.0"?>
<!-- Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root. -->
<!DOCTYPE sortOrder SYSTEM "AlphaSort1_0.dtd">
<sortOrder>  
   <sortValue>
      <unicode>
         <hex> 0410 </hex>
      </unicode>
      <unicode>
         <hex> 0430 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0411 </hex>
      </unicode>
      <unicode>
         <hex> 0431 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0412 </hex>
      </unicode>
      <unicode>
         <hex> 0432 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0413 </hex>
      </unicode>
      <unicode>
         <hex> 0433 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0414 </hex>
      </unicode>
      <unicode>
         <hex> 0434 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0415 </hex>
      </unicode>
      <unicode>
         <hex> 0435 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0416 </hex>
      </unicode>
      <unicode>
         <hex> 0436 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0417 </hex>
      </unicode>
      <unicode>
         <hex> 0437 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0418 </hex>
      </unicode>
      <unicode>
         <hex> 0438 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0419 </hex>
      </unicode>
      <unicode>
         <hex> 0439 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 041A </hex>
      </unicode>
      <unicode>
         <hex> 043A </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 041B </hex>
      </unicode>
      <unicode>
         <hex> 043B </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 041C </hex>
      </unicode>
      <unicode>
         <hex> 043C </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 041D </hex>
      </unicode>
      <unicode>
         <hex> 043D </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 041E </hex>
      </unicode>
      <unicode>
         <hex> 043E </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 041F </hex>
      </unicode>
      <unicode>
         <hex> 043F </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0420 </hex>
      </unicode>
      <unicode>
         <hex> 0440 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0421 </hex>
      </unicode>
      <unicode>
         <hex> 0441 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0422 </hex>
      </unicode>
      <unicode>
         <hex> 0442 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0423 </hex>
      </unicode>
      <unicode>
         <hex> 0443 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0424 </hex>
      </unicode>
      <unicode>
         <hex> 0444 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0425 </hex>
      </unicode>
      <unicode>
         <hex> 0445 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0426 </hex>
      </unicode>
      <unicode>
         <hex> 0446 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0427 </hex>
      </unicode>
      <unicode>
         <hex> 0447 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0428 </hex>
      </unicode>
      <unicode>
         <hex> 0448 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0429 </hex>
      </unicode>
      <unicode>
         <hex> 0449 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 042A </hex>
      </unicode>
      <unicode>
         <hex> 044A </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 042B </hex>
      </unicode>
      <unicode>
         <hex> 044B </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 042C </hex>
      </unicode>
      <unicode>
         <hex> 044C </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 042D </hex>
      </unicode>
      <unicode>
         <hex> 044D </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 042E </hex>
      </unicode>
      <unicode>
         <hex> 044E </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 042F </hex>
      </unicode>
      <unicode>
         <hex> 044F </hex>
      </unicode>
   </sortValue>
</sortOrder>

=== wiltonlazary/vespa/vespalib/src/vespa/fastlib/text/alphasort/Arabic.xml
<?xml version="1.0"?>
<!-- Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root. -->
<!DOCTYPE sortOrder SYSTEM "AlphaSort1_0.dtd">
<sortOrder>  
   <sortValue>
      <unicode>
         <hex> 0627 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0628 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0629 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 062A </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 062B </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 062C </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 062D </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 062E </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 062F </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0630 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0631 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0632 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0633 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0634 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0635 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0636 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0637 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0638 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0639 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 063A </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0641 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0642 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0643 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0644 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0645 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0646 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0647 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0648 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 0649 </hex>
      </unicode>
   </sortValue>
   <sortValue>
      <unicode>
         <hex> 064A </hex>
      </unicode>
   </sortValue>
</sortOrder>
