=== wiltonlazary/vespa/vespalib/src/vespa/fastlib/text/alphasort/SortMaster1_0.dtd
<!--  (c) 2002 Fast Search & Transfer. All rights reserved.  -->
<!-- Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root. -->
<!--  Version 1.0 -->

<!ELEMENT masterFile (sortValueWidth, importFiles)>
<!ELEMENT importFiles (importFile+)>
<!ELEMENT sortValueWidth (#PCDATA)>
<!ELEMENT importFile (#PCDATA)>

=== wiltonlazary/vespa/vespalib/src/vespa/fastlib/text/alphasort/AlphaSortMasterFile.xml
<?xml version="1.0"?>
<!-- Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root. -->
<!DOCTYPE masterFile SYSTEM "SortMaster1_0.dtd">
<masterFile>
   <sortValueWidth> 8 </sortValueWidth>
   <importFiles>
      <importFile>Space.xml</importFile>
      <importFile>Numbers.xml</importFile>
      <importFile>Latin.xml</importFile>
      <importFile>Arabic.xml</importFile>
      <importFile>Hebrew.xml</importFile>
      <importFile>Cyrillic.xml</importFile>
      <importFile>Greek.xml</importFile>
      <importFile>Kana.xml</importFile>
   </importFiles>
</masterFile>
